# Generated by Django 4.0.4 on 2022-12-06 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('name', models.CharField(help_text='Enter the team name (e.g. Royal Challengers Bangalore)', max_length=50, primary_key=True, serialize=False)),
                ('captain', models.CharField(help_text='Enter the team captain name (e.g. Virat Kohli)', max_length=100)),
                ('owner', models.CharField(help_text='Enter the team owner name (e.g. Vijay Mallya)', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('pid', models.IntegerField(help_text='Enter Unique Player ID', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter the player name (e.g. Virat Kohli)', max_length=50)),
                ('role', models.CharField(help_text='Enter the player role (e.g. Batsman)', max_length=100)),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='matchSchedule.team')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue', models.CharField(help_text='Enter the game venue (e.g. Bangalore)', max_length=100)),
                ('team1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='GameTeam1', to='matchSchedule.team')),
                ('team2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='GameTeam2', to='matchSchedule.team')),
            ],
        ),
    ]
