# Generated by Django 4.0.4 on 2022-12-06 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchSchedule', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Players',
            new_name='Player',
        ),
    ]
