# Generated by Django 4.0.4 on 2022-12-06 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchSchedule', '0002_rename_players_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='team1',
            field=models.CharField(help_text='Enter the team name (e.g. Royal Challengers Bangalore)', max_length=100),
        ),
        migrations.AlterField(
            model_name='game',
            name='team2',
            field=models.CharField(help_text='Enter the team name (e.g. Royal Challengers Bangalore)', max_length=100),
        ),
    ]
